# fly.toml app configuration file generated for simpchapp-wandering-dawn-7315 on 2025-04-01T15:11:17-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simply-chat-app'
primary_region = 'dfw'

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"
 
[[services]]
  http_checks = []
  internal_port = 5050
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  http_checks = []
  internal_port = 5051
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 5051

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 5051

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[http_service]
  min_machines_running = 1